version: '3.9'
services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: flotilla
      POSTGRES_DB: flotilla
      POSTGRES_PASSWORD: flotilla

volumes:
  dbdata: