version: '3.9'
services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: flotilla
      POSTGRES_DB: flotilla
      POSTGRES_PASSWORD: flotilla
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: flotilla
      RABBITMQ_DEFAULT_PASS: flotilla
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  dbdata: